# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(526, 259)
        Dialog.setStyleSheet("background-color: rgb(236, 252, 255);\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 441, 41))
        self.label.setStyleSheet("\n"
"font: 75 26pt \"Lucida Sans\";\n"
"color: rgb(0, 168, 209);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(390, 90, 101, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"border-radius:8px;\n"
"font: 75 11pt \"Lucida Sans\";\n"
"    color: rgb(236, 252, 255);\n"
"    background-color: rgb(0, 168, 209);\n"
"border-color: rgb(105, 210, 231);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 91, 371, 61))
        self.listWidget.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"")
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(21, 197, 471, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius:8px;\n"
"font: 75 11pt \"Lucida Sans\";\n"
"    color: rgb(236, 252, 255);\n"
"    background-color: rgb(0, 168, 209);\n"
"border-color: rgb(105, 210, 231);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius:8px;\n"
"font: 75 11pt \"Lucida Sans\";\n"
"    color: rgb(236, 252, 255);\n"
"    background-color: rgb(0, 168, 209);\n"
"border-color: rgb(105, 210, 231);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Pdf maker"))
        self.pushButton.setText(_translate("Dialog", "Browse files"))
        self.pushButton_2.setText(_translate("Dialog", "Merge pdf"))
        self.pushButton_3.setText(_translate("Dialog", "Make pdf"))
